name: pipeline

on:
  push:
    branches:
      - master

env:
  SOLN_FILE: Saucery3.sln               # set this to your application's name
  CONFIG: Release
  APP_PACKAGE_PATH: 'published'        # set this to the path to your web app project, defaults to the repository root

      
jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v1

    - name: Setup MSBuild Path
      uses: warrenbuckley/Setup-MSBuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
      
    - name: Restore NuGet Packages
      run: nuget restore ${{ env.SOLN_FILE }}

    - name: Build App
      run: msbuild ${{ env.SOLN_FILE }} /p:Configuration=${{ env.CONFIG }}

    #- name: Setup MSBuild
    #  uses: warrenbuckley/Setup-MSBuild@v1
    #- name: Build with MSBuild
    #  run: msbuild  ${{ env.APP_NAME }} -p:Configuration=${{ env.CONFIG }}