name: pipeline

on:
  push:
    branches:
      - master

env:
  SOLN_FILE: Saucery3.sln               # set this to your application's name
  CONFIG: Release
  APP_PACKAGE_PATH: 'published'        # set this to the path to your web app project, defaults to the repository root

      
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master
    - uses: nuget/setup-nuget@v1
    - run: nuget restore ${{ env.SOLN_FILE }}
    
    #- name: Setup MSBuild
    #  uses: warrenbuckley/Setup-MSBuild@v1
    #- name: Build with MSBuild
    #  run: msbuild  ${{ env.APP_NAME }} -p:Configuration=${{ env.CONFIG }}